[changelog]
header = "# Changelog"
body = """
Alle relevanten Ã„nderungen an diesem Projekt werden in dieser Datei dokumentiert.
"""

[git]
conventional_commits = true
filter_commits = true
tag_pattern = "v[0-9]*"

[git.commit_parsers]
"feat" = { group = "ğŸš€ Features" }
"fix" = { group = "ğŸ Bugfixes" }
"refactor" = { group = "â™»ï¸ Refactoring" }
"perf" = { group = "âš¡ Performance" }
"docs" = { group = "ğŸ“ Dokumentation" }
"test" = { group = "âœ… Tests" }
"build" = { group = "ğŸ—ï¸ Build" }
"ci" = { group = "ğŸ” CI" }
"chore" = { group = "ğŸ”§ Wartung" }

[git.tag_parsers]
"v(.*)" = "$1"
